stage:
    - docker-build

docker_build:
  stage: docker-build
  # image: docker:24.0.5
  # services:
  #   - docker:24.0.5-dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER  https://gitlab.com --password-stdin
    - docker build -t https://gitlab.com/smr1234/sample-web:latest .
    - docker push https://gitlab.com/smr1234/sample-web:latest
    - docker images 


