apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJzbXIxMjM0IiwicGFzc3dvcmQiOiJTYWhhbmFoa0AxMjMiLCJhdXRoIjoiYzIxeU1USXpORHBUWVdoaGJtRm9hMEF4TWpNPSJ9fX0=
kind: Secret
metadata:
  name: my-secret-todo
type: kubernetes.io/dockerconfigjson

