apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2dpdGxhYi5jb20iOnsidXNlcm5hbWUiOiJzbXIxMjMiLCJwYXNzd29yZCI6IlNhaGFuYWhrQDEyMyIsImF1dGgiOiJjMjF5TVRJek9sTmhhR0Z1WVdoclFERXlNdz09In19fQ==
kind: Secret
metadata:
  namespace: webapp
  name: my-secret
type: kubernetes.io/dockerconfigjson

