apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: webapp
spec:
  selector:
    app: webapp
  ports:
    - name: webapp-service
      protocol: TCP
      port: 80
      targetPort: 8090 
  type: NodePort

