apiVersion: v1
kind: Service
metadata:
  name: spring-service
  labels:
    app: spring
spec:
  selector:
    app: spring
  ports:
    - name: spring-service
      protocol: TCP
      port: 80
      targetPort: 8085  
  type: NodePort

